<a href="https://colab.research.google.com/github/AnviTendulkar/Airline_Fare_Prediction/blob/master/Untitled00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# pip install --upgrade scikit-learn
!pip install category_encoders

Requirement already satisfied: category_encoders in /usr/local/lib/python3.10/dist-packages (2.6.3)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.23.5)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.11.4)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.1)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.2.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (23.2)

In [2]:
# y_train.to_frame(name='Price')

In [3]:
import pandas as pd
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import FunctionTransformer ,OneHotEncoder
# from sklearn.preprocessing import TargetEncoder
import category_encoders as ce
from datetime import datetime , timedelta

In [4]:
pd.set_option("display.max_columns" ,None)

In [5]:
train_data = pd.read_excel(r'/content/drive/MyDrive/Project/Final Airline/Data_Train.xlsx')

In [6]:
train_data.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662

In [7]:
train_data.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [8]:
missing_data = train_data[train_data['Route'].isnull()]
missing_data

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
9039,Air India,6/05/2019,Delhi,Cochin,NaN,09:45,09:25 07 May,23h 40m,NaN,No info,7480

In [9]:
train_data = train_data.dropna()

In [10]:
# imputer = KNNImputer()
# missing_data[['Route' ,'Total_Stops']]  = imputer.fit_transform(missing_data[['Route' ,'Total_Stops']])

In [11]:
train_data[train_data['Route'].isnull()]

Empty DataFrame
Columns: [Airline, Date_of_Journey, Source, Destination, Route, Dep_Time, Arrival_Time, Duration, Total_Stops, Additional_Info, Price]
Index: []

In [12]:
X = train_data.loc[: , train_data.columns != 'Price']
y = train_data.loc[:,'Price']
x_train ,x_val_set , y_train ,y_val_test =train_test_split(X,y,test_size =0.20,random_state =42)

In [13]:
class DateExtractor(BaseEstimator ,TransformerMixin):
  def fit(self , X,y =None):
      return self
  def transformer():
    journey_date = datetime.strftrain_data['Date_of_Journey']

In [14]:
def date_time_preprocessig(df):
  df['Date_of_Journey'] = pd.to_datetime(df['Date_of_Journey'] ,format = '%d/%m/%Y')
  df['journey_day'] = df['Date_of_Journey'].dt.day
  df['journey_month'] = df['Date_of_Journey'].dt.month
  df['journey_year'] = df['Date_of_Journey'].dt.year
  df[['dep_hour' , 'dep_minute']] = df['Dep_Time'].str.split(':' ,expand=True)
  df.drop(columns=['Date_of_Journey','Dep_Time'] , inplace=True)
  print("ddd = ",df)
  return df

In [15]:
def total_stops_preprocessor(df):
  df['Total_Stops'] = df['Total_Stops'].replace({'1 stop': 1, 'non-stop': 0, '2 stops': 2, '3 stops': 3, '4 stops': 4})
  return df

In [16]:
def Arrival_Date_calculation(row):
    pattern = re.compile(r'(?:(\d+)h)?\s?(?:(\d+)m)?')
    match = pattern.match(row['Duration'])
    if match:
        hours = int(match.group(1)) if match.group(1) else 0
        minutes = int(match.group(2)) if match.group(2) else 0

    # Concatenate 'Date_of_Journey' and 'Dep_Time'
    row['Duration'] = (hours * 60 ) + minutes
    date_of_journey = row['Date_of_Journey'] + ' ' + row['Dep_Time']

    # Convert the concatenated string to datetime
    journey_date_time = datetime.strptime(date_of_journey, "%d/%m/%Y %H:%M")

    # Calculate arrival date by adding 'Duration_hour' and 'Duration_minute' to 'Date_of_Journey'
    arrival_date = journey_date_time + timedelta(hours=hours, minutes=minutes)
    return arrival_date

In [17]:
class ArrivalTimeCalculator(BaseEstimator, TransformerMixin):
    def fit(self, df, y=None):
        return self

    def transform(self, df):
        date1 = df.apply(Arrival_Date_calculation ,axis=1)
        df['Arrival_Year'] = date1.dt.year
        df['Arrival_Month'] = date1.dt.month
        df['Arrival_Day'] = date1.dt.day
        df['Arrival_hour'] = date1.dt.hour
        df['Arrival_minute'] = date1.dt.minute

        print(type(df['Arrival_Year']),df.head(2))
        df.drop(columns=['Date_of_Journey','Dep_Time'] , inplace=True)
        return df

    def get_feature_names_out(self, input_features=None):
        # Return the output feature names after transformation
        # print("xxxx = ",df.columns)
        # return ['Date_of_Journey', 'Dep_Time']+['Arrival_Year' ,'Arrival_Month' ,'Arrival_Day','Duration']
        return ['Duration','Arrival_Year' ,'Arrival_Month' ,'Arrival_Day','Arrival_hour','Arrival_minute']


    # def get_params(self, deep=True):

    #     return {}

In [18]:
preprocessing = ColumnTransformer([
    ('airline' ,ce.TargetEncoder(),['Airline']),
    ('one-hot', OneHotEncoder(drop='first', sparse_output=False, dtype='int16' ,handle_unknown = 'ignore'), [ 2, 3]) ,
    ('date_time_preprocessig' ,FunctionTransformer(date_time_preprocessig ,validate =False),['Date_of_Journey' ,'Dep_Time' ] ) ,
    ('ArrivalTimeCalculator', ArrivalTimeCalculator(), ['Date_of_Journey', 'Dep_Time','Duration']),
    ('total_stop',FunctionTransformer(total_stops_preprocessor,validate =False) , ['Total_Stops'])
] )

In [19]:
clf =Pipeline([('preprocessing' ,preprocessing)])
m = clf.fit_transform(x_train,y_train)

ddd =         journey_day  journey_month  journey_year dep_hour dep_minute
10005           27              5          2019       08         30
3684             9              5          2019       11         30
1034            24              4          2019       15         45
3909            21              3          2019       12         50
3088            24              6          2019       17         15
...            ...            ...           ...      ...        ...
5734            27              3          2019       09         00
5191             9              5          2019       14         05
5390            15              5          2019       12         50
860              3              3          2019       00         40
7270             1              6          2019       13         00

[8545 rows x 5 columns]
<class 'pandas.core.series.Series'>       Date_of_Journey Dep_Time Duration  Arrival_Year  Arrival_Month  \
10005      27/05/2019    08:30      645          2019              5
3684        9/05/2019    11:30     1505          2019              5

       Arrival_Day  Arrival_hour  Arrival_minute
10005           27            19              15
3684            10            12              35

In [20]:
m[:3,:]

array([[10910.46750524109, 0, 1, 0, 0, 1, 0, 0, 0, 0, 27, 5, 2019, '08',
        '30', 645, 2019, 5, 27, 19, 15, 1],
       [11616.945591609308, 0, 1, 0, 0, 1, 0, 0, 0, 0, 9, 5, 2019, '11',
        '30', 1505, 2019, 5, 10, 12, 35, 1],
       [4359.854714064915, 0, 1, 0, 0, 1, 0, 0, 0, 0, 24, 4, 2019, '15',
        '45', 380, 2019, 4, 24, 22, 5, 1]], dtype=object)

In [21]:
one_hot_columns = preprocessing.named_transformers_['one-hot'].get_feature_names_out(['Source', 'Destination'])
transformed_columns = ['Airline']+list(one_hot_columns) + ['journey_day','journey_month','journey_year','dep_hour','dep_minute']+preprocessing.named_transformers_['ArrivalTimeCalculator'].get_feature_names_out(['Date_of_Journey', 'Dep_Time','Duration']) +  ['Total_Stops']
print(transformed_columns)
transformed_df = pd.DataFrame(m ,columns = transformed_columns)
transformed_df.head(5)

['Airline', 'Source_Chennai', 'Source_Delhi', 'Source_Kolkata', 'Source_Mumbai', 'Destination_Cochin', 'Destination_Delhi', 'Destination_Hyderabad', 'Destination_Kolkata', 'Destination_New Delhi', 'journey_day', 'journey_month', 'journey_year', 'dep_hour', 'dep_minute', 'Duration', 'Arrival_Year', 'Arrival_Month', 'Arrival_Day', 'Arrival_hour', 'Arrival_minute', 'Total_Stops']

,Airline,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,journey_day,journey_month,journey_year,dep_hour,dep_minute,Duration,Arrival_Year,Arrival_Month,Arrival_Day,Arrival_hour,Arrival_minute,Total_Stops
0,10910.467505,0,1,0,0,1,0,0,0,0,27,5,2019,08,30,645,2019,5,27,19,15,1
1,11616.945592,0,1,0,0,1,0,0,0,0,9,5,2019,11,30,1505,2019,5,10,12,35,1
2,4359.854714,0,1,0,0,1,0,0,0,0,24,4,2019,15,45,380,2019,4,24,22,5,1
3,10910.467505,0,1,0,0,1,0,0,0,0,21,3,2019,12,50,765,2019,3,22,1,35,1
4,9708.081662,0,1,0,0,1,0,0,0,0,24,6,2019,17,15,1560,2019,6,25,19,15,2

In [30]:
transformed_df['Price'] = y_train.values
transformed_df.head(5)

,Airline,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi,journey_day,journey_month,journey_year,dep_hour,dep_minute,Duration,Arrival_Year,Arrival_Month,Arrival_Day,Arrival_hour,Arrival_minute,Total_Stops,Price
0,10910.467505,0,1,0,0,1,0,0,0,0,27,5,2019,08,30,645,2019,5,27,19,15,1,9149
1,11616.945592,0,1,0,0,1,0,0,0,0,9,5,2019,11,30,1505,2019,5,10,12,35,1,12373
2,4359.854714,0,1,0,0,1,0,0,0,0,24,4,2019,15,45,380,2019,4,24,22,5,1,5583
3,10910.467505,0,1,0,0,1,0,0,0,0,21,3,2019,12,50,765,2019,3,22,1,35,1,7695
4,9708.081662,0,1,0,0,1,0,0,0,0,24,6,2019,17,15,1560,2019,6,25,19,15,2,11972

# Feature Selection

In [28]:
train_data[train_data['Price']==7662.0]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
162,Air India,9/06/2019,Kolkata,Banglore,CCU → BBI → BLR,12:00,13:15 10 Jun,25h 15m,1 stop,No info,7662
2059,Air India,24/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2202,Air India,6/06/2019,Kolkata,Banglore,CCU → GAU → BLR,16:45,21:05 07 Jun,28h 20m,1 stop,No info,7662
3326,Air India,6/06/2019,Kolkata,Banglore,CCU → BBI → BLR,12:00,13:15 07 Jun,25h 15m,1 stop,No info,7662
4331,Air India,24/05/2019,Kolkata,Banglore,CCU → GAU → BLR,09:50,21:05,11h 15m,1 stop,No info,7662
4653,Air India,12/06/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
4984,Air India,21/05/2019,Kolkata,Banglore,CCU → BBI → BLR,12:00,13:15 22 May,25h 15m,1 stop,No info,7662
5540,Air India,9/06/2019,Kolkata,Banglore,CCU → GAU → BLR,16:45,21:05 10 Jun,28h 20m,1 stop,No info,7662
5705,Air India,9/06/2019,Kolkata,Banglore,CCU → GAU → BLR,09:50,21:05,11h 15m,1 stop,No info,7662
7103,Air India,6/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
7130,Air India,12/05/2019,Kolkata,Banglore,CCU → GAU → BLR,16:45,21:05 13 May,28h 20m,1 stop,No info,7662
8023,Air India,18/05/2019,Kolkata,Banglore,CCU → BBI → BLR,12:00,13:15 19 May,25h 15m,1 stop,No info,7662
10350,Air India,9/05/2019,Kolkata,Banglore,CCU → GAU → BLR,16:45,21:05 10 May,28h 20m,1 stop,No info,7662

In [29]:
y_val_test

6075     16655
3544      4959
9291      9187
5032      3858
2483     12898
         ...
9797      7408
9871      4622
10063     7452
8802      8824
8617     14151
Name: Price, Length: 2137, dtype: int64